In [1]:
import numpy as np

a = np.array([1,2,3])
print("np.array:",a)
print("=====================")

b = np.zeros((2,3))
print("np.zeros:",b)
print("=====================")

c= np.ones((2,3))
print("np.ones:",c)
print("=====================")

e= np.arange(-2,5)
print("np.arange:",e)
print("=====================")

f=np.linspace(1,5,6)
print("np.linspace:",f)
print("=====================")

g= np.indices((2,3))
print("np.indices:",g)
print("=====================")

np.array: [1 2 3]
np.zeros: [[0. 0. 0.]
 [0. 0. 0.]]
np.ones: [[1. 1. 1.]
 [1. 1. 1.]]
np.arange: [-2 -1  0  1  2  3  4]
np.linspace: [1.  1.8 2.6 3.4 4.2 5. ]
np.indices: [[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]
